version: '3'
services:
  nginx-router:
    build: ./NginxRouter
    ports:
      - "80:80"
    depends_on:
      - create-project
    volumes:
      - ./events:/events
  create-project:
    build: ./CreateProject
    ports:
      - "5001:80"
    volumes:
      - ./events:/events  
    environment:
      EVENT_PATH: /events
      ASPNETCORE_URLS: https://+:80
  approve:
    build: ./Approve
    ports:
      - "5002:80"
    volumes:
      - ./events:/events
    environment:
      EVENT_PATH: /events
      ASPNETCORE_URLS: https://+:80
  submit-timesheet:
    build: ./SubmitTimesheet
    ports:
      - "5003:80"
    volumes:
      - ./events:/events
    environment:
      EVENT_PATH: /events
      ASPNETCORE_URLS: https://+:80